export const regions = [
  {
    id: 67,
    count: 13,
    description: '',
    link: 'https://sales.airsells.ca/region/alberta/',
    name: 'Alberta',
    slug: 'alberta',
    taxonomy: 'region',
    parent: 0,
    meta: [],
    _cover: '1937',
    cover:
      'https://sales.airsells.ca/wp-content/uploads/2019/12/anna-newell-7ZBZHaw6L_c-unsplash-1.jpg',
  },
  {
    id: 56,
    count: 16,
    description: '',
    link: 'https://sales.airsells.ca/region/new-brunswick/',
    name: 'New Brunswick',
    slug: 'new-brunswick',
    taxonomy: 'region',
    parent: 0,
    meta: [],
    _cover: '1328',
    cover:
      'https://sales.airsells.ca/wp-content/uploads/2019/10/bay-of-fundy-new-brunswick-canada_980x650.jpg',
  },
  {
    id: 55,
    count: 1,
    description: '',
    link: 'https://sales.airsells.ca/region/nova-scotia/',
    name: 'Nova Scotia',
    slug: 'nova-scotia',
    taxonomy: 'region',
    parent: 0,
    meta: [],
    _cover: '1329',
    cover:
      'https://sales.airsells.ca/wp-content/uploads/2019/10/lighthouse-and-coastal-landscape-in-nova-scotia-1024x683.jpg',
  },
  {
    id: 28,
    count: 39,
    description: '',
    link: 'https://sales.airsells.ca/region/ontario/',
    name: 'Ontario',
    slug: 'ontario',
    taxonomy: 'region',
    parent: 0,
    meta: [],
    _cover: '1331',
    cover:
      'https://sales.airsells.ca/wp-content/uploads/2019/10/Ontario_h_00000218865162.adapt_.1900.1-1024x682.jpg',
  },
  {
    id: 32,
    count: 15,
    description: '',
    link: 'https://sales.airsells.ca/region/prince-edward-island/',
    name: 'Prince Edward Island',
    slug: 'prince-edward-island',
    taxonomy: 'region',
    parent: 0,
    meta: [],
    _cover: '1924',
    cover:
      'https://sales.airsells.ca/wp-content/uploads/2019/12/Prince_Edward_Island.jpg',
  },
];

export const categories = {
  29: [
    {
      id: 1596,
      date: '2019-11-08T15:38:53',
      date_gmt: '2019-11-08T19:38:53',
      guid: {
        rendered: 'http://sufianlocal.local/listing/sample-202/',
      },
      modified: '2019-11-22T19:35:03',
      modified_gmt: '2019-11-22T23:35:03',
      slug: 'sample-202',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/sample-202/',
      title: {
        rendered: 'Sample 202',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 12,
      featured_media: 0,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [29],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27],
      region: [32],
      'listeo-avg-rating': '0',
      _submitting_key: '5dc5c4485f599',
      listing_title: 'Sample 202',
      keywords: '',
      product_id: '1595',
      _address: '92 Kent Street, Charlottetown, PE, Canada',
      _geolocation_long: '-63.129745000000014',
      _geolocation_lat: '46.234748',
      _gallery: '',
      _thumbnail_id: '',
      listing_description: '',
      _price_min: '15',
      _price_max: '10',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: 'men',
              description: '',
              price: '20',
              bookable: 'on',
            },
            {
              name: 'women',
              description: '',
              price: '20',
              bookable: '',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["06:00 am - 06:30 am|4|","09:00 am - 09:30 am|1|","10:00 am - 10:30 am|1|"],["09:00 am - 09:30 am|1|"],[],[],[],[],[]]',
      _normal_price: '0',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights: 'jj',
      _what_youll_get: 'j',
      _requirements: 'jj',
      _get_to_know_us: 'j',
      _booking_: 'j',
      _delivery_: 'j',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '33',
      _edit_last: '',
      slide_template: '',
      _edit_lock: '',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: '',
      _event_tickets_sold: '0',
      _gallery_style: '',
    },
    {
      id: 1587,
      date: '2019-11-08T14:37:49',
      date_gmt: '2019-11-08T18:37:49',
      guid: {
        rendered: 'http://sufianlocal.local/listing/sample-2-2/',
      },
      modified: '2019-11-08T15:45:37',
      modified_gmt: '2019-11-08T19:45:37',
      slug: 'sample-201',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/sample-201/',
      title: {
        rendered: 'sample 201',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 12,
      featured_media: 0,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [29],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27],
      region: [28],
      'listeo-avg-rating': '0',
      _submitting_key: '5dc5b5fb1fb82',
      listing_title: 'sample 201',
      keywords: '',
      product_id: '1586',
      _address: '108 Kent Street, Ottawa, ON, Canada',
      _geolocation_long: '-75.70311509999999',
      _geolocation_lat: '45.4198756',
      _gallery: '',
      _thumbnail_id: '',
      listing_description: '',
      _price_min: '120',
      _price_max: '100',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: 'sample 1',
              description: '',
              price: '20',
              bookable: 'on',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["06:00 am - 06:30 am|4","09:00 am - 09:30 am|1","10:00 am - 10:30 am|1"],["09:00 am - 09:30 am|1"],[],[],["05:00 pm - 06:00 pm|1"],[],[]]',
      _normal_price: '20',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights: 'h',
      _what_youll_get: 'h',
      _requirements: 'h',
      _get_to_know_us: 'h',
      _booking_: 'hg',
      _delivery_: 'j',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '58',
      _edit_last: '',
      slide_template: '',
      _edit_lock: '',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: 'sample-2-2',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
    {
      id: 1585,
      date: '2019-11-08T14:36:01',
      date_gmt: '2019-11-08T18:36:01',
      guid: {
        rendered: 'http://sufianlocal.local/listing/sample1/',
      },
      modified: '2019-11-22T18:27:27',
      modified_gmt: '2019-11-22T22:27:27',
      slug: 'sample102',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/sample102/',
      title: {
        rendered: 'sample102',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 12,
      featured_media: 0,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [29],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22],
      region: [28],
      'listeo-avg-rating': '0',
      _submitting_key: '5dc5b58e595ef',
      listing_title: 'sample102',
      keywords: '',
      product_id: '1584',
      _address: '109 Kent Street, Ottawa, ON, Canada',
      _geolocation_long: '-75.70311579999998',
      _geolocation_lat: '45.4198764',
      _gallery: '',
      _thumbnail_id: '',
      listing_description: '',
      _price_min: '15',
      _price_max: '10',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: 'sample 1',
              description: '',
              price: '20',
              bookable: 'on',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["06:00 am - 06:15 am|1|1622","06:15 am - 06:30 am|1|1622","06:30 am - 06:45 am|1|1622"],["09:00 am - 09:30 am|1|"],[],[],[],[],[]]',
      _normal_price: '20',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights: 'h',
      _what_youll_get: 'g',
      _requirements: 'h',
      _get_to_know_us: 'g',
      _booking_: 'g',
      _delivery_: 'f',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '78',
      _edit_last: '',
      slide_template: '',
      _edit_lock: '',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: 'sample1',
      _event_tickets_sold: '0',
      _gallery_style: '',
    },
    {
      id: 1549,
      date: '2019-11-03T14:32:26',
      date_gmt: '2019-11-03T18:32:26',
      guid: {
        rendered: 'http://sufianlocal.local/listing/sample-2/',
      },
      modified: '2019-11-17T19:52:06',
      modified_gmt: '2019-11-17T23:52:06',
      slug: 'check-new',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/check-new/',
      title: {
        rendered: 'check new',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 8,
      featured_media: 0,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [29],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [],
      region: [28],
      'listeo-avg-rating': '0',
      _submitting_key: '5dbf1d356de47',
      listing_title: 'check new',
      keywords: '',
      product_id: '0',
      _address: '92 Kent Street West, Lindsay, ON, Canada',
      _geolocation_long: '-78.7380771',
      _geolocation_lat: '44.3549781',
      _gallery: '',
      _thumbnail_id: '',
      listing_description: '',
      _price_min: '10',
      _price_max: '',
      _email_contact_widget: 'check_on',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: 'Evan',
              description: 'dd',
              price: '12',
              bookable: 'on',
            },
            {
              name: 'Adeel',
              description: '',
              price: '',
              bookable: 'on',
            },
            {
              name: 'Sufian',
              description: '',
              price: '',
              bookable: 'on',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["09:00 am - 09:30 am|10|1622","09:00 am - 09:30 am|1|"],[],[],[],[],[],[]]',
      _normal_price: '120',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights: 'ee',
      _what_youll_get: 'dd',
      _requirements: 'dd',
      _get_to_know_us: 'd',
      _booking_: '',
      _delivery_: '',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '35',
      _edit_last: '',
      slide_template: '',
      _edit_lock: '',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: 'sample-2',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
    {
      id: 1415,
      date: '2019-10-19T16:55:12',
      date_gmt: '2019-10-19T19:55:12',
      guid: {
        rendered: 'https://dev.airsells.ca/?post_type=listing&#038;p=1415',
      },
      modified: '2019-10-19T17:02:25',
      modified_gmt: '2019-10-19T20:02:25',
      slug: 'vitality-treatment-2',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/vitality-treatment-2/',
      title: {
        rendered: 'Vitality Treatment',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 8,
      featured_media: 1366,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [29],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27, 23],
      region: [56],
      'listeo-avg-rating': '0',
      _submitting_key: '5dab5e0ef3a30',
      listing_title: 'Vitality Treatment',
      keywords: 'Treatment, Beauty',
      product_id: '0',
      _address: 'Moncton, NB, Canada',
      _geolocation_long: '-64.77823130000002',
      _geolocation_lat: '46.0878165',
      _gallery: {
        '1363': 'Face Treatment 8.jpg',
        '1364': 'Face Treatment 6.jpg',
        '1365': 'Face Treatment 2.jpg',
        '1366': 'Face Treatment 1.jpg',
      },
      _thumbnail_id: '1366',
      listing_description: '',
      _price_min: '102',
      _price_max: '102',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: '75 minute treatment',
              description: '',
              price: '80',
              bookable: 'on',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["09:00 am - 09:30 am|1"],["09:00 am - 09:30 am|1"],["09:30 am - 10:00 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|2"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"]]',
      _normal_price: '102',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights:
        'Microdermabrasion, a skin resurfacing treatment to eliminate dead cells and to enhance collagen production, followed by a soothing mask.',
      _what_youll_get: '<ul>\r\n \t<li>75 minute treatment</li>\r\n</ul>',
      _requirements: '',
      _get_to_know_us:
        'We are the largest spa in the greater moncton area. Our aim at Spa Medes is to provide an atmosphere of calm and serenity where you can unwind and relax with our experienced estheticians or massage therapists for a few minutes or a few hours.',
      _booking_: 'Pick an available time slot and make a payment.',
      _delivery_: '',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '57',
      _edit_last: '8',
      slide_template: '',
      _edit_lock: '1571514919:8',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: '',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
    {
      id: 1414,
      date: '2019-10-19T16:54:37',
      date_gmt: '2019-10-19T19:54:37',
      guid: {
        rendered: 'https://dev.airsells.ca/?post_type=listing&#038;p=1414',
      },
      modified: '2019-10-19T17:02:08',
      modified_gmt: '2019-10-19T20:02:08',
      slug: 'paramedical-facial-3',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/paramedical-facial-3/',
      title: {
        rendered: 'Paramedical Facial',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 8,
      featured_media: 1371,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [29],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27, 23],
      region: [56],
      'listeo-avg-rating': '0',
      _submitting_key: '5dab5eb76543a',
      listing_title: 'Paramedical Facial',
      keywords: 'facial, paramedical',
      product_id: '0',
      _address: 'Moncton, NB, Canada',
      _geolocation_long: '-64.77823130000002',
      _geolocation_lat: '46.0878165',
      _gallery: {
        '1368': 'Face Treatment 6.jpg',
        '1369': 'Face Treatment 1.jpg',
        '1370': 'Face Treatment 2.jpg',
        '1371': 'Face Treatment 3.jpg',
      },
      _thumbnail_id: '1371',
      listing_description: '',
      _price_min: '102',
      _price_max: '102',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: '75 Minute Facial',
              description: '',
              price: '102',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],[],[],[],[]]',
      _normal_price: '102',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights:
        'Specialized facial with products from Physiodermie, a superior skin care line composed of the highest quality natural ingredients. This treatment offers an advanced method to penetrate in the most profound layers of skin.',
      _what_youll_get:
        '<ul>\r\n \t<li>75 minute session for $102</li>\r\n</ul>',
      _requirements: '',
      _get_to_know_us:
        'We are the largest spa in the greater moncton area. Our aim at Spa Medes is to provide an atmosphere of calm and serenity where you can unwind and relax with our experienced estheticians or massage therapists for a few minutes or a few hours.',
      _booking_: 'Pick an available time slot and make a payment.',
      _delivery_: '',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '28',
      _edit_last: '8',
      slide_template: '',
      _edit_lock: '1571514901:8',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: '',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
    {
      id: 1372,
      date: '2019-10-19T16:06:34',
      date_gmt: '2019-10-19T19:06:34',
      guid: {
        rendered: 'https://dev.airsells.ca/listing/paramedical-facial-2/',
      },
      modified: '2019-10-19T16:06:34',
      modified_gmt: '2019-10-19T19:06:34',
      slug: 'paramedical-facial-2',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/paramedical-facial-2/',
      title: {
        rendered: 'Paramedical Facial',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 8,
      featured_media: 1370,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [29],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27, 23],
      region: [56],
      'listeo-avg-rating': '0',
      _submitting_key: '5dab5eb76543a',
      listing_title: 'Paramedical Facial',
      keywords: 'facial, paramedical',
      product_id: '0',
      _address: 'Moncton, NB, Canada',
      _geolocation_long: '-64.77823130000002',
      _geolocation_lat: '46.0878165',
      _gallery: {
        '1368': 'Face Treatment 6.jpg',
        '1369': 'Face Treatment 1.jpg',
        '1370': 'Face Treatment 2.jpg',
        '1371': 'Face Treatment 3.jpg',
      },
      _thumbnail_id: '1370',
      listing_description: '',
      _price_min: '102',
      _price_max: '102',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: '75 Minute Facial',
              description: '',
              price: '102',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],[],[],[],[]]',
      _normal_price: '102',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights:
        'Specialized facial with products from Physiodermie, a superior skin care line composed of the highest quality natural ingredients. This treatment offers an advanced method to penetrate in the most profound layers of skin.',
      _what_youll_get:
        '<ul>\r\n \t<li>75 minute session for $102</li>\r\n</ul>',
      _requirements: '',
      _get_to_know_us:
        'We are the largest spa in the greater moncton area. Our aim at Spa Medes is to provide an atmosphere of calm and serenity where you can unwind and relax with our experienced estheticians or massage therapists for a few minutes or a few hours.',
      _booking_: 'Pick an available time slot and make a payment.',
      _delivery_: '',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '18',
      _edit_last: '',
      slide_template: '',
      _edit_lock: '',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: '',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
    {
      id: 1367,
      date: '2019-10-19T16:03:47',
      date_gmt: '2019-10-19T19:03:47',
      guid: {
        rendered: 'https://dev.airsells.ca/listing/vitality-treatment/',
      },
      modified: '2019-10-19T16:03:47',
      modified_gmt: '2019-10-19T19:03:47',
      slug: 'vitality-treatment',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/vitality-treatment/',
      title: {
        rendered: 'Vitality Treatment',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 8,
      featured_media: 1364,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [29],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27, 23],
      region: [56],
      'listeo-avg-rating': '0',
      _submitting_key: '5dab5e0ef3a30',
      listing_title: 'Vitality Treatment',
      keywords: 'Treatment, Beauty',
      product_id: '0',
      _address: 'Moncton, NB, Canada',
      _geolocation_long: '-64.77823130000002',
      _geolocation_lat: '46.0878165',
      _gallery: {
        '1363': 'Face Treatment 8.jpg',
        '1364': 'Face Treatment 6.jpg',
        '1365': 'Face Treatment 2.jpg',
        '1366': 'Face Treatment 1.jpg',
      },
      _thumbnail_id: '1364',
      listing_description: '',
      _price_min: '102',
      _price_max: '102',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: '75 minute treatment',
              description: '',
              price: '80',
              bookable: 'on',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["09:00 am - 09:30 am|1"],["09:00 am - 09:30 am|1"],["09:30 am - 10:00 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|2"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"]]',
      _normal_price: '102',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights:
        'Microdermabrasion, a skin resurfacing treatment to eliminate dead cells and to enhance collagen production, followed by a soothing mask.',
      _what_youll_get: '<ul>\r\n \t<li>75 minute treatment</li>\r\n</ul>',
      _requirements: '',
      _get_to_know_us:
        'We are the largest spa in the greater moncton area. Our aim at Spa Medes is to provide an atmosphere of calm and serenity where you can unwind and relax with our experienced estheticians or massage therapists for a few minutes or a few hours.',
      _booking_: 'Pick an available time slot and make a payment.',
      _delivery_: '',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '19',
      _edit_last: '',
      slide_template: '',
      _edit_lock: '',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: '',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
  ],
  34: [
    {
      id: 1418,
      date: '2019-10-19T16:55:43',
      date_gmt: '2019-10-19T19:55:43',
      guid: {
        rendered: 'https://dev.airsells.ca/?post_type=listing&#038;p=1418',
      },
      modified: '2019-10-31T17:15:00',
      modified_gmt: '2019-10-31T20:15:00',
      slug: 'condo-cleaning-2',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/condo-cleaning-2/',
      title: {
        rendered: 'Condo Cleaning',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 8,
      featured_media: 0,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [34],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27, 23],
      region: [32],
      'listeo-avg-rating': '0',
      _submitting_key: '5daa97554c89a',
      listing_title: 'Condo Cleaning',
      keywords: '',
      product_id: '0',
      _address: '92 Kent Street, Charlottetown, PE, Canada',
      _geolocation_long: '-63.12971100000004',
      _geolocation_lat: '46.2347224',
      _gallery: {
        '1345': 'House Cleaning 4.jpg',
        '1346': 'House Cleaning 5.jpg',
        '1348': 'House Cleaning Art.jpg',
      },
      _thumbnail_id: '',
      listing_description: '',
      _price_min: '20',
      _price_max: '10',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: 'One additional bathroom',
              description: '',
              price: '25',
              bookable: 'on',
            },
            {
              name: 'one additional bedroom',
              description: '',
              price: '30',
              bookable: 'on',
            },
          ],
        },
        {
          menu_elements: [
            {
              name: 'One additional bedroom and bathroom',
              description: '',
              price: '50',
              bookable: 'on',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],[],[]]',
      _normal_price: '120',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights:
        'Save your time for more rewarding activities and save your condo cleaning duties to the professionals at MOLLY MAID. You are free to pursue outside interests or entertain at home with the assurance that our team has taken care of every bit of dust and every smidge of dirt. Professionally trained, bonded and insured, the team members we send for your condo cleaning are prepared with the equipment and supplies they need. Request a regularly scheduled or one-time cleaning that is customized to your needs.',
      _what_youll_get:
        '<ul>\r\n \t<li>Detailed cleaning of your kitchen and two bathrooms</li>\r\n \t<li>Washing all floors and cabinet exteriors</li>\r\n \t<li>Spot cleaning of walls</li>\r\n \t<li>Dusting of pictures, baseboards, window sills, furniture, light fixtures and lamp shades</li>\r\n \t<li>Complete vacuuming of three rooms.</li>\r\n</ul>',
      _requirements: '',
      _get_to_know_us:
        'MOLLY MAID offers a flexible and customized maid service at an affordable price, based on a free, no-obligation, in-home estimate. Professionally trained, bonded and insured staff work in teams of two to efficiently clean your home. They arrive in MOLLY MAID decaled cars and bring all necessary cleaning equipment and supplies.',
      _booking_:
        'Pick an available time slot and make a payment, you can also pick additional services if you want to add more bathroom or rooms. If you have any special instructions, please message us ahead of your appointment or you can also add those during the checkout process.',
      _delivery_: '',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '19',
      _edit_last: '8',
      slide_template: '',
      _edit_lock: '1571514950:8',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: '',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
    {
      id: 1417,
      date: '2019-10-19T16:55:41',
      date_gmt: '2019-10-19T19:55:41',
      guid: {
        rendered: 'https://dev.airsells.ca/?post_type=listing&#038;p=1417',
      },
      modified: '2019-10-19T17:04:38',
      modified_gmt: '2019-10-19T20:04:38',
      slug: 'house-cleaning',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/house-cleaning/',
      title: {
        rendered: 'House Cleaning',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 8,
      featured_media: 1346,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [34],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27, 23],
      region: [32],
      'listeo-avg-rating': '0',
      _submitting_key: '5daa97554c89a',
      listing_title: 'House Cleaning',
      keywords: '',
      product_id: '0',
      _address: '92 Kent Street, Charlottetown, PE, Canada',
      _geolocation_long: '-63.12971100000004',
      _geolocation_lat: '46.2347224',
      _gallery: {
        '1345': 'House Cleaning 4.jpg',
        '1346': 'House Cleaning 5.jpg',
        '1347': 'House Cleaning 3.jpg',
        '1348': 'House Cleaning Art.jpg',
      },
      _thumbnail_id: '1346',
      listing_description: '',
      _price_min: '20',
      _price_max: '10',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: 'One additional bathroom',
              description: '',
              price: '25',
              bookable: 'on',
            },
            {
              name: 'one additional bedroom',
              description: '',
              price: '30',
              bookable: 'on',
            },
          ],
        },
        {
          menu_elements: [
            {
              name: 'One additional bedroom and bathroom',
              description: '',
              price: '50',
              bookable: 'on',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],[],[]]',
      _normal_price: '90',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights:
        'Save your time for more rewarding activities and save your condo cleaning duties to the professionals at MOLLY MAID. You are free to pursue outside interests or entertain at home with the assurance that our team has taken care of every bit of dust and every smidge of dirt. Professionally trained, bonded and insured, the team members we send for your condo cleaning are prepared with the equipment and supplies they need. Request a regularly scheduled or one-time cleaning that is customized to your needs.',
      _what_youll_get:
        '<ul>\r\n \t<li>Detailed cleaning of your kitchen and two bathrooms</li>\r\n \t<li>Washing all floors and cabinet exteriors</li>\r\n \t<li>Spot cleaning of walls</li>\r\n \t<li>Dusting of pictures, baseboards, window sills, furniture, light fixtures and lamp shades</li>\r\n \t<li>Complete vacuuming of three rooms.</li>\r\n</ul>',
      _requirements: '',
      _get_to_know_us:
        'MOLLY MAID offers a flexible and customized maid service at an affordable price, based on a free, no-obligation, in-home estimate. Professionally trained, bonded and insured staff work in teams of two to efficiently clean your home. They arrive in MOLLY MAID decaled cars and bring all necessary cleaning equipment and supplies.',
      _booking_:
        'Pick an available time slot and make a payment, you can also pick additional services if you want to add more bathroom or rooms. If you have any special instructions, please message us ahead of your appointment or you can also add those during the checkout process.',
      _delivery_: '',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '16',
      _edit_last: '8',
      slide_template: '',
      _edit_lock: '1571514962:8',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: '',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
    {
      id: 1416,
      date: '2019-10-19T16:55:38',
      date_gmt: '2019-10-19T19:55:38',
      guid: {
        rendered: 'https://dev.airsells.ca/?post_type=listing&#038;p=1416',
      },
      modified: '2019-10-19T17:04:49',
      modified_gmt: '2019-10-19T20:04:49',
      slug: 'airbnb-cleaning-service',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/airbnb-cleaning-service/',
      title: {
        rendered: 'Airbnb Cleaning Service',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 8,
      featured_media: 1348,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [34],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27, 23],
      region: [32],
      'listeo-avg-rating': '0',
      _submitting_key: '5daa97554c89a',
      listing_title: 'Airbnb Cleaning Service',
      keywords: '',
      product_id: '0',
      _address: '92 Kent Street, Charlottetown, PE, Canada',
      _geolocation_long: '-63.12971100000004',
      _geolocation_lat: '46.2347224',
      _gallery: {
        '1345': 'House Cleaning 4.jpg',
        '1346': 'House Cleaning 5.jpg',
        '1347': 'House Cleaning 3.jpg',
        '1348': 'House Cleaning Art.jpg',
      },
      _thumbnail_id: '1348',
      listing_description: '',
      _price_min: '20',
      _price_max: '10',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: 'One additional bathroom',
              description: '',
              price: '25',
              bookable: 'on',
            },
            {
              name: 'one additional bedroom',
              description: '',
              price: '30',
              bookable: 'on',
            },
          ],
        },
        {
          menu_elements: [
            {
              name: 'One additional bedroom and bathroom',
              description: '',
              price: '50',
              bookable: 'on',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],[],[]]',
      _normal_price: '70',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights:
        'Save your time for more rewarding activities and save your condo cleaning duties to the professionals at MOLLY MAID. You are free to pursue outside interests or entertain at home with the assurance that our team has taken care of every bit of dust and every smidge of dirt. Professionally trained, bonded and insured, the team members we send for your condo cleaning are prepared with the equipment and supplies they need. Request a regularly scheduled or one-time cleaning that is customized to your needs.',
      _what_youll_get:
        '<ul>\r\n \t<li>Detailed cleaning of your kitchen and two bathrooms</li>\r\n \t<li>Washing all floors and cabinet exteriors</li>\r\n \t<li>Spot cleaning of walls</li>\r\n \t<li>Dusting of pictures, baseboards, window sills, furniture, light fixtures and lamp shades</li>\r\n \t<li>Complete vacuuming of three rooms.</li>\r\n</ul>',
      _requirements: '',
      _get_to_know_us:
        'MOLLY MAID offers a flexible and customized maid service at an affordable price, based on a free, no-obligation, in-home estimate. Professionally trained, bonded and insured staff work in teams of two to efficiently clean your home. They arrive in MOLLY MAID decaled cars and bring all necessary cleaning equipment and supplies.',
      _booking_:
        'Pick an available time slot and make a payment, you can also pick additional services if you want to add more bathroom or rooms. If you have any special instructions, please message us ahead of your appointment or you can also add those during the checkout process.',
      _delivery_: '',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '10',
      _edit_last: '8',
      slide_template: '',
      _edit_lock: '1571514997:8',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: '',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
    {
      id: 1349,
      date: '2019-10-19T01:55:58',
      date_gmt: '2019-10-19T04:55:58',
      guid: {
        rendered: 'https://dev.airsells.ca/listing/condo-cleaning/',
      },
      modified: '2019-10-19T16:44:49',
      modified_gmt: '2019-10-19T19:44:49',
      slug: 'condo-cleaning',
      status: 'publish',
      type: 'listing',
      link: 'http://airsells.local/listing/condo-cleaning/',
      title: {
        rendered: 'Condo Cleaning',
      },
      content: {
        rendered: '',
        protected: false,
      },
      author: 8,
      featured_media: 1345,
      comment_status: 'open',
      ping_status: 'closed',
      template: '',
      meta: [],
      listing_category: [34],
      event_category: [],
      service_category: [],
      rental_category: [],
      listing_feature: [30, 22, 27, 23],
      region: [32],
      'listeo-avg-rating': '0',
      _submitting_key: '5daa97554c89a',
      listing_title: 'Condo Cleaning',
      keywords: '',
      product_id: '0',
      _address: '92 Kent Street, Charlottetown, PE, Canada',
      _geolocation_long: '-63.12971100000004',
      _geolocation_lat: '46.2347224',
      _gallery: {
        '1345': 'House Cleaning 4.jpg',
        '1346': 'House Cleaning 5.jpg',
        '1347': 'House Cleaning 3.jpg',
        '1348': 'House Cleaning Art.jpg',
      },
      _thumbnail_id: '1345',
      listing_description: '',
      _price_min: '20',
      _price_max: '10',
      _email_contact_widget: '',
      _opening_hours_status: '',
      _opening_hours:
        '[{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""},{"opening":"","closing":""}]',
      _monday_opening_hour: '',
      _monday_closing_hour: '',
      _tuesday_opening_hour: '',
      _tuesday_closing_hour: '',
      _wednesday_opening_hour: '',
      _wednesday_closing_hour: '',
      _thursday_opening_hour: '',
      _thursday_closing_hour: '',
      _friday_opening_hour: '',
      _friday_closing_hour: '',
      _saturday_opening_hour: '',
      _saturday_closing_hour: '',
      _sunday_opening_hour: '',
      _sunday_closing_hour: '',
      _menu_status: 'on',
      _menu: [
        {
          menu_elements: [
            {
              name: 'One additional bathroom',
              description: '',
              price: '25',
              bookable: 'on',
            },
            {
              name: 'one additional bedroom',
              description: '',
              price: '30',
              bookable: 'on',
            },
          ],
        },
        {
          menu_elements: [
            {
              name: 'One additional bedroom and bathroom',
              description: '',
              price: '50',
              bookable: 'on',
            },
          ],
        },
      ],
      _hide_pricing_if_bookable: '',
      _booking_status: 'on',
      _slots_status: 'on',
      _slots:
        '[["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],["10:00 am - 10:30 am|1"],[],[]]',
      _normal_price: '110',
      _expired_after: '',
      _instant_booking: 'check_on',
      _max_guests: '',
      _count_per_guest: '',
      _listing_type: 'service',
      _highlights:
        'Save your time for more rewarding activities and save your condo cleaning duties to the professionals at MOLLY MAID. You are free to pursue outside interests or entertain at home with the assurance that our team has taken care of every bit of dust and every smidge of dirt. Professionally trained, bonded and insured, the team members we send for your condo cleaning are prepared with the equipment and supplies they need. Request a regularly scheduled or one-time cleaning that is customized to your needs.',
      _what_youll_get:
        '<ul>\r\n \t<li>Detailed cleaning of your kitchen and two bathrooms</li>\r\n \t<li>Washing all floors and cabinet exteriors</li>\r\n \t<li>Spot cleaning of walls</li>\r\n \t<li>Dusting of pictures, baseboards, window sills, furniture, light fixtures and lamp shades</li>\r\n \t<li>Complete vacuuming of three rooms.</li>\r\n</ul>',
      _requirements: '',
      _get_to_know_us:
        'MOLLY MAID offers a flexible and customized maid service at an affordable price, based on a free, no-obligation, in-home estimate. Professionally trained, bonded and insured staff work in teams of two to efficiently clean your home. They arrive in MOLLY MAID decaled cars and bring all necessary cleaning equipment and supplies.',
      _booking_:
        'Pick an available time slot and make a payment, you can also pick additional services if you want to add more bathroom or rooms. If you have any special instructions, please message us ahead of your appointment or you can also add those during the checkout process.',
      _delivery_: '',
      _listing_expires: '',
      listeo_published_mail_send: 'sent',
      _listing_views_count: '8',
      _edit_last: '8',
      slide_template: '',
      _edit_lock: '1571514289:8',
      _event_date: '',
      _event_date_end: '',
      _event_tickets: '',
      _reservation_price: '',
      _wp_old_slug: '',
      _event_tickets_sold: '',
      _gallery_style: '',
    },
  ],
};
